version: '2.1'

services:

  db:
    container_name: ${DB_CONTAINER}
    image: mysql:${MYSQL_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - ${MYSQL_HTTP_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  adminer:
    image: adminer:${ADMINER_TAG}
    restart: always
    ports:
      - ${ADMINER_HTTP_PORT}:8080
