version: '2.1'

services:

  node:
    container_name: ${NODE_CONTAINER}
    image: node:${TAG}
    hostname: ${NODE_HOSTNAME}
    user: 'node'
    environment:
      - NODE_ENV='production'
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - '${HTTP_PORT}:3000'
    command: [npm, start]
    restart: always
